# Generated by Django 4.2.5 on 2024-02-08 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messanger_chat', '0002_alter_message_options_room_privat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='privat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='privat', to='messanger_chat.userpage'),
        ),
    ]
